### ISSUE TITLE
Problem with getImportContent does not work correctly

### ISSUE THREAD

**Issue by StefH** [alincode/solcjs-core#1]
When trying to compile the base contract:  https://github.com/mstack/bootcamp-blockchain-smartcontracts/blob/master/Lab%204%20(SupplyChainLog)/Solidity/contracts/SupplyChainLogContract.sol

Which uses code like:
```
pragma solidity ^0.5.2;


import "./OrderContract.sol";


contract SupplyChainLogContract is OrderContract {

    // Constructor
    constructor () public {
        owner = msg.sender;
    }
}
```

This code does not resolve correctly:

![image](https://user-images.githubusercontent.com/249938/57458824-50444380-7272-11e9-9dad-8e7eb205011e.png)

And when I try to use
`import "OrderContract.sol";`

I get this error
![image](https://user-images.githubusercontent.com/249938/57459223-13c51780-7273-11e9-9d50-6013295e8077.png)

Can you please help me?

**Comment by alincode** [comment]
if you want to use import, you need to use`solc-resolver` module.
otherwise, it can't find where is xxx.sol.

you can see some example here.
https://github.com/alincode/solcjs-lightweight

**Comment by StefH** [comment]
I don't need that resolver because I've written my own resolver:
``` js
const output = await compiler(this.mainContract.content, async (contractFilename) => {
  const contractName = this.sanitizeFilename(contractFilename);
  console.log(`Resolving contract '${contractFilename}' (${contractName})`);

  const contractContent = this.otherContracts[contractName];
  console.log(`contractContent found = ${contractContent}`);

  return {
    contents: contractContent
  };
});
```

The problem is that
(1)  search path has no "./"
(2) the `sources` does have a "./"

![image](https://user-images.githubusercontent.com/249938/57468223-59d6a700-7284-11e9-96ae-dc019910dd87.png)

Which results into error:
```
TypeError: Cannot read property 'contents' of undefined
    at Array.eval (wrapper.js?e4a0:12)
    at jsCall_viii (<anonymous>:1:1181003)
    at Array.Hwb (<anonymous>:11:796308)
    at Array._c (<anonymous>:8:5328)
    at Object.Gwb [as dynCall_viii] (<anonymous>:11:796256)
    at invoke_viii (<anonymous>:1:1180838)
    at Array.Ex (<anonymous>:9:329447)
    at Object.iyb [as dynCall_viiii] (<anonymous>:11:802423)
    at invoke_viiii (<anonymous>:1:1181888)
    at Dx (<anonymous>:9:323972)
```
![image](https://user-images.githubusercontent.com/249938/57469463-01ed6f80-7287-11e9-8239-b96a6641d858.png)

**Comment by alincode** [comment]
solc core does not care about the path (so that is why I made a solc-resolver module). for it, every path just a string. if you don't give to it a right mapping. it can't find a file content.

I think your `getImportContext` implement is incorrect, you might check it again.

I tested your contract in my test case. anything is working fine.

![螢幕快照 2019-05-11 上午8 45 00](https://user-images.githubusercontent.com/7610755/57562903-efc81a00-73c9-11e9-9de4-65a8a50b90c7.png)

or you can use https://github.com/ethereum-play/solc-js

solcjs-core is a low level module, solc-js is a high low module. it includes Integration many modules.

**Comment by StefH** [comment]
Thanks for you help and this project.

I'm able to get it running with this code:
![image](https://user-images.githubusercontent.com/249938/57566306-323e2680-73cb-11e9-81c8-a10c67275c5f.png)

However, using a "./" in the import still fails. See also this issue : https://github.com/alincode/solcjs-lightweight/issues/1
